# Form implementation generated from reading ui file 'calculator_style.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 457)
        MainWindow.setStyleSheet("background-color: #1E1E2E;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(0, 0, 351, 101))
        self.outputLabel.setStyleSheet("\n"
"    color: #00E5FF;  /* Neon Cyan */\n"
"    font-size: 40px;\n"
"    font-weight: bold;\n"
"    qproperty-alignment: \'AlignRight | AlignVCenter\';\n"
"    padding: 15px;\n"
"    background-color: #292A3A; /* Dark Gray */\n"
"    border-radius: 10px;\n"
"    width: 320px;\n"
"    height: 70px;")
        self.outputLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 110, 331, 326))
        self.gridLayoutWidget.setStyleSheet("")
        self.gridLayoutWidget.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Kyrgyzstan))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.oneButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget, clicked=lambda: self.press_it('1'))
        self.oneButton.setStyleSheet("font-size: 24px;\n"
"    font-weight: bold;\n"
"    border-radius: 70px;\n"
"padding:5px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: 5px;\n"
"background-color: #3A3B4F; /* Darker Blue */\n"
"    color: white;\n"
"")
        self.oneButton.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Kyrgyzstan))
        self.oneButton.setObjectName("oneButton")
        self.gridLayout.addWidget(self.oneButton, 3, 0, 1, 1)
        self.equalButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget, clicked=lambda: self.press_it('='))
        self.equalButton.setStyleSheet("font-size: 24px;\n"
"    font-weight: bold;\n"
"    border-radius: 70px;\n"
"padding: 5px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: 5px;\n"
"background-color: #00A6FF; \n"
"    color: white;")
        self.equalButton.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Kyrgyzstan))
        self.equalButton.setObjectName("equalButton")
        self.gridLayout.addWidget(self.equalButton, 4, 3, 1, 1)
        self.threeButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget, clicked=lambda: self.press_it('3'))
        self.threeButton.setStyleSheet("font-size: 24px;\n"
"    font-weight: bold;\n"
"    border-radius: 70px;\n"
"padding:5px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: 5px;\n"
"background-color: #3A3B4F; /* Darker Blue */\n"
"    color: white;\n"
"")
        self.threeButton.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Kyrgyzstan))
        self.threeButton.setObjectName("threeButton")
        self.gridLayout.addWidget(self.threeButton, 3, 2, 1, 1)
        self.nineButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget, clicked=lambda: self.press_it('9'))
        self.nineButton.setStyleSheet("font-size: 24px;\n"
"    font-weight: bold;\n"
"    border-radius: 70px;\n"
"padding:5px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: 5px;\n"
"background-color: #3A3B4F; /* Darker Blue */\n"
"    color: white;\n"
"")
        self.nineButton.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Kyrgyzstan))
        self.nineButton.setObjectName("nineButton")
        self.gridLayout.addWidget(self.nineButton, 1, 2, 1, 1)
        self.minusButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget, clicked=lambda: self.press_it('-'))
        self.minusButton.setStyleSheet("font-size: 24px;\n"
"    font-weight: bold;\n"
"    border-radius: 70px;\n"
"padding: 5px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: 5px;\n"
"background-color: #00A6FF; \n"
"    color: white;")
        self.minusButton.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Kyrgyzstan))
        self.minusButton.setObjectName("minusButton")
        self.gridLayout.addWidget(self.minusButton, 2, 3, 1, 1)
        self.plusminusButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget, clicked=lambda: self.press_it('+/-'))
        self.plusminusButton.setStyleSheet("font-size: 24px;\n"
"    font-weight: bold;\n"
"    border-radius: 70px;\n"
"padding: 5px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: 5px;\n"
"background-color: #00A6FF; \n"
"    color: white;\n"
"")
        self.plusminusButton.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Kyrgyzstan))
        self.plusminusButton.setObjectName("plusminusButton")
        self.gridLayout.addWidget(self.plusminusButton, 4, 0, 1, 1)
        self.sixButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget, clicked=lambda: self.press_it('6'))
        self.sixButton.setStyleSheet("font-size: 24px;\n"
"    font-weight: bold;\n"
"    border-radius: 70px;\n"
"padding:5px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: 5px;\n"
"background-color: #3A3B4F; /* Darker Blue */\n"
"    color: white;\n"
"")
        self.sixButton.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Kyrgyzstan))
        self.sixButton.setObjectName("sixButton")
        self.gridLayout.addWidget(self.sixButton, 2, 2, 1, 1)
        self.zeroButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget, clicked=lambda: self.press_it('0'))
        self.zeroButton.setStyleSheet("font-size: 24px;\n"
"    font-weight: bold;\n"
"    border-radius: 70px;\n"
"padding:5px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: 5px;\n"
"background-color: #3A3B4F; /* Darker Blue */\n"
"    color: white;")
        self.zeroButton.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Kyrgyzstan))
        self.zeroButton.setObjectName("zeroButton")
        self.gridLayout.addWidget(self.zeroButton, 4, 1, 1, 1)
        self.plusButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget, clicked=lambda: self.press_it('+'))
        self.plusButton.setStyleSheet("font-size: 24px;\n"
"    font-weight: bold;\n"
"    border-radius: 70px;\n"
"padding: 5px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: 5px;\n"
"background-color: #00A6FF; \n"
"    color: white;")
        self.plusButton.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Kyrgyzstan))
        self.plusButton.setObjectName("plusButton")
        self.gridLayout.addWidget(self.plusButton, 3, 3, 1, 1)
        self.fourButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget, clicked=lambda: self.press_it('4'))
        self.fourButton.setStyleSheet("font-size: 24px;\n"
"    font-weight: bold;\n"
"    border-radius: 70px;\n"
"padding:5px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: 5px;\n"
"background-color: #3A3B4F; /* Darker Blue */\n"
"    color: white;\n"
"")
        self.fourButton.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Kyrgyzstan))
        self.fourButton.setObjectName("fourButton")
        self.gridLayout.addWidget(self.fourButton, 2, 0, 1, 1)
        self.fiveButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget, clicked=lambda: self.press_it('5'))
        self.fiveButton.setStyleSheet("font-size: 24px;\n"
"    font-weight: bold;\n"
"    border-radius: 70px;\n"
"padding:5px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: 5px;\n"
"background-color: #3A3B4F; /* Darker Blue */\n"
"    color: white;\n"
"")
        self.fiveButton.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Kyrgyzstan))
        self.fiveButton.setObjectName("fiveButton")
        self.gridLayout.addWidget(self.fiveButton, 2, 1, 1, 1)
        self.multiplyButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget, clicked=lambda: self.press_it('*'))
        self.multiplyButton.setStyleSheet("font-size: 24px;\n"
"    font-weight: bold;\n"
"    border-radius: 70px;\n"
"padding: 5px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: 5px;\n"
"background-color: #00A6FF; \n"
"    color: white;")
        self.multiplyButton.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Kyrgyzstan))
        self.multiplyButton.setObjectName("multiplyButton")
        self.gridLayout.addWidget(self.multiplyButton, 1, 3, 1, 1)
        self.eightButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget, clicked=lambda: self.press_it('8'))
        self.eightButton.setStyleSheet("font-size: 24px;\n"
"    font-weight: bold;\n"
"    border-radius: 70px;\n"
"padding:5px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: 5px;\n"
"background-color: #3A3B4F; /* Darker Blue */\n"
"    color: white;\n"
"")
        self.eightButton.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Kyrgyzstan))
        self.eightButton.setObjectName("eightButton")
        self.gridLayout.addWidget(self.eightButton, 1, 1, 1, 1)
        self.sevenButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget, clicked=lambda: self.press_it('7'))
        self.sevenButton.setStyleSheet("font-size: 24px;\n"
"    font-weight: bold;\n"
"    border-radius: 70px;\n"
"padding:5px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: 5px;\n"
"background-color: #3A3B4F; /* Darker Blue */\n"
"    color: white;\n"
"")
        self.sevenButton.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Kyrgyzstan))
        self.sevenButton.setObjectName("sevenButton")
        self.gridLayout.addWidget(self.sevenButton, 1, 0, 1, 1)
        self.decimalButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget, clicked=lambda: self.press_it('.'))
        self.decimalButton.setStyleSheet("font-size: 30px;\n"
"    font-weight: bold;\n"
"    border-radius: 70px;\n"
"padding: 5px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: 5px;\n"
"background-color: #00A6FF; \n"
"    color: white;")
        self.decimalButton.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Kyrgyzstan))
        self.decimalButton.setObjectName("decimalButton")
        self.gridLayout.addWidget(self.decimalButton, 4, 2, 1, 1)
        self.twoButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget, clicked=lambda: self.press_it('2'))
        self.twoButton.setStyleSheet("font-size: 24px;\n"
"    font-weight: bold;\n"
"    border-radius: 70px;\n"
"padding:5px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: 5px;\n"
"background-color: #3A3B4F; /* Darker Blue */\n"
"    color: white;\n"
"")
        self.twoButton.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Russian, QtCore.QLocale.Country.Kyrgyzstan))
        self.twoButton.setObjectName("twoButton")
        self.gridLayout.addWidget(self.twoButton, 3, 1, 1, 1)
        self.clearButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget, clicked=lambda: self.press_it('C'))
        self.clearButton.setStyleSheet("font-size: 24px;\n"
"    font-weight: bold;\n"
"    border-radius: 70px;\n"
"padding: 5px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: 5px;\n"
"background-color: #00A6FF; \n"
"    color: white;")
        self.clearButton.setObjectName("clearButton")
        self.gridLayout.addWidget(self.clearButton, 0, 1, 1, 1)
        self.percentButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget, clicked=lambda: self.press_it('%'))
        self.percentButton.setStyleSheet("font-size: 24px;\n"
"    font-weight: bold;\n"
"    border-radius: 70px;\n"
"padding: 5px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: 5px;\n"
"background-color: #00A6FF; \n"
"    color: white;")
        self.percentButton.setObjectName("percentButton")
        self.gridLayout.addWidget(self.percentButton, 0, 0, 1, 1)
        self.delButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget, clicked=lambda: self.press_it('del'))
        self.delButton.setStyleSheet("font-size: 20px;\n"
"    font-weight: bold;\n"
"    border-radius: 70px;\n"
"padding: 5px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: 5px;\n"
"background-color: #00A6FF; \n"
"    color: white;")
        self.delButton.setObjectName("delButton")
        self.gridLayout.addWidget(self.delButton, 0, 2, 1, 1)
        self.divideButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget, clicked=lambda: self.press_it('/'))
        self.divideButton.setStyleSheet("font-size: 24px;\n"
"    font-weight: bold;\n"
"    border-radius: 70px;\n"
"padding: 5px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"    margin: 5px;\n"
"background-color: #00A6FF; \n"
"    color: white;")
        self.divideButton.setObjectName("divideButton")
        self.gridLayout.addWidget(self.divideButton, 0, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.outputLabel.setText(_translate("MainWindow", "0"))
        self.oneButton.setText(_translate("MainWindow", "1"))
        self.equalButton.setText(_translate("MainWindow", "="))
        self.threeButton.setText(_translate("MainWindow", "3"))
        self.nineButton.setText(_translate("MainWindow", "9"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.plusminusButton.setText(_translate("MainWindow", "+/-"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.plusButton.setText(_translate("MainWindow", "+"))
        self.fourButton.setText(_translate("MainWindow", "4"))
        self.fiveButton.setText(_translate("MainWindow", "5"))
        self.multiplyButton.setText(_translate("MainWindow", "×"))
        self.eightButton.setText(_translate("MainWindow", "8"))
        self.sevenButton.setText(_translate("MainWindow", "7"))
        self.decimalButton.setText(_translate("MainWindow", "."))
        self.twoButton.setText(_translate("MainWindow", "2"))
        self.clearButton.setText(_translate("MainWindow", "AC"))
        self.percentButton.setText(_translate("MainWindow", "%"))
        self.delButton.setText(_translate("MainWindow", "⌫"))
        self.divideButton.setText(_translate("MainWindow", "÷"))

    def press_it(self, pressed):
        if pressed == 'C':
            self.outputLabel.setText('0')
        else:
            if self.outputLabel.text() == '0':
                self.outputLabel.setText('')
            self.outputLabel.setText(f'{self.outputLabel.text()}{pressed}')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
"C:\Users\User\Documents\Python\oop_learning\calculator_gui"